markdown: kramdown
highlighter: rouge

# Site wide configuration

description       : Blog
title             : Programlama Dilleri ile ilgili Yazilar
keywords          : C,Language,Programming
logo              : siteicon.png
search            : false
baseurl           : ""
url               : https://vdemir.github.io
author:
  name            : "GÃ¼nce"
  url             : https://vdemir.github.io
  email           : jeruselam@yandex.com
  bio             : "Just another tattooed, time traveling designer."
  picture         : ""

yandex-verify     : "b642748cb18cbd1c"
google-verify     : "zFuwF6tlf7YemTRN-ZOvl5lG1rjuI9qEomPbr_5vAu8"


comments:
  provider: "disqus"
  disqus:
    shortname: "vdemir-github-io"


